In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
a=pd.read_csv("dataset/student1.csv")

In [4]:
a

        Reg_no                                  Name
0   393CS21707                       VARSHA GALAGALI
1   393CS20001              ABHINAV PRASANNA NAIKODI
2   393CS20001              ABHINAV PRASANNA NAIKODI
3   393CS20002                          AKASH TORAVI
4   393CS21702              BIRADAR GURURAJ SIDHARUD
5   393CS20005                DUGIWADE PRACHI SANJAY
6   393CS21703                   GURUNATH DESHAPANDE
7   393CS20006           HARSHAD MAHAMMADSAB WALIKAR
8   393CS20007                    IRAMNAAZ JAMKHANDI
9   393CS20001              ABHINAV PRASANNA NAIKODI
10  393CS20008                   JAHID ALI BALABATTI
11  393CS20009                KRISHNA MAHADEV JADHAV
12  393CS20010                        LAXMI NAVALAGI
13  393CS20011                      MAIBOOBSAB NADAF
14  393CS21704                  MANJU SHIVAJI CHAVAN
15  393CS20012                  MISBA BUDANSAB MOMIN
16  393CS20013                   MODI AVADOOT MAHESH
17  393CS20015                     NADAF NIHAL NASIM
18  393CS20016                    NANDINI NITIN MODI
19  393CS20017               NEELAVANI VARSHA VITTAL
20  393CS20018                            NEHA PATIL
21  393CS20019                               NIKHEEL
22  393CS20020                POOJA RAJSHEKHAR ARABI
23  393CS20022                       PRAJWAL D DHAGE
24  393CS20023                        RENUKA ARAKERI
25  393CS20024                        ROSHANI KUMARI
26  393CS20025  SACHIDANANDA MADIVALESHA BEVINAMARAD
27  393CS20026                   SHAREEKA GUDIYATTAM
28  393CS21706                  SNEHA ASHOK DODAMANI
29  393CS20028                        SPURTI S PATIL
30  393CS20029                       TANISHK BIRADAR
31  393CS20030                         UMARBIN PATIL
32  393CS21707                       VARSHA GALAGALI
33  393CS20018                            NEHA PATIL
34  393CS17018                        RAHUL BADAKURI
35  393CS20031                 VIDYA BABUGOUDA PATIL
36  393CS20032                       VIVEK CHOUDHARY
37  393CS17009          HAVINAL SHRIDHAR MALLIKARJUN
38  393CS17015                     OMKAR SHARANARTHI
39  393CS17018                        RAHUL BADAKURI
40  393CS21702              BIRADAR GURURAJ SIDHARUD
41  393CS21703                   GURUNATH DESHAPANDE
42  393CS21704                  MANJU SHIVAJI CHAVAN
43  393CS21706                  SNEHA ASHOK DODAMANI
44  393CS21707                       VARSHA GALAGALI
45  393CS20008                   JAHID ALI BALABATTI
46  393CS21706                  SNEHA ASHOK DODAMANI
47  393CS20028                        SPURTI S PATIL
48  393CS20030                         UMARBIN PATIL

In [11]:
b=pd.read_csv("dataset/marks1.csv")

In [12]:
b

    OSA  CN
0    44  45
1    97  47
2    97  47
3    97  52
4    75  21
5    11  23
6    87  92
7    45  78
8    97  17
9    97  47
10   23  45
11   87  65
12   61  39
13   33  39
14   53  44
15   56  62
16   22  65
17   45  20
18   25  15
19   90  74
20   31  94
21   93   3
22   41  89
23   32  57
24   90  91
25   76  72
26   17  30
27   58  49
28    4  24
29   86  70
30   24  87
31   20  11
32   37  58
33   31  94
34    7  31
35   95  77
36   61  84
37   88  83
38   76  31
39    7  31
40   77  70
41   43  27
42   10  14
43   90  22
44   44  45
45   23  45
46    4  24
47   86  70
48   20  11

In [13]:
df=pd.concat([a,b],axis=1)

In [14]:
df

        Reg_no                                  Name  OSA  CN
0   393CS21707                       VARSHA GALAGALI   44  45
1   393CS20001              ABHINAV PRASANNA NAIKODI   97  47
2   393CS20001              ABHINAV PRASANNA NAIKODI   97  47
3   393CS20002                          AKASH TORAVI   97  52
4   393CS21702              BIRADAR GURURAJ SIDHARUD   75  21
5   393CS20005                DUGIWADE PRACHI SANJAY   11  23
6   393CS21703                   GURUNATH DESHAPANDE   87  92
7   393CS20006           HARSHAD MAHAMMADSAB WALIKAR   45  78
8   393CS20007                    IRAMNAAZ JAMKHANDI   97  17
9   393CS20001              ABHINAV PRASANNA NAIKODI   97  47
10  393CS20008                   JAHID ALI BALABATTI   23  45
11  393CS20009                KRISHNA MAHADEV JADHAV   87  65
12  393CS20010                        LAXMI NAVALAGI   61  39
13  393CS20011                      MAIBOOBSAB NADAF   33  39
14  393CS21704                  MANJU SHIVAJI CHAVAN   53  44
15  393CS20012                  MISBA BUDANSAB MOMIN   56  62
16  393CS20013                   MODI AVADOOT MAHESH   22  65
17  393CS20015                     NADAF NIHAL NASIM   45  20
18  393CS20016                    NANDINI NITIN MODI   25  15
19  393CS20017               NEELAVANI VARSHA VITTAL   90  74
20  393CS20018                            NEHA PATIL   31  94
21  393CS20019                               NIKHEEL   93   3
22  393CS20020                POOJA RAJSHEKHAR ARABI   41  89
23  393CS20022                       PRAJWAL D DHAGE   32  57
24  393CS20023                        RENUKA ARAKERI   90  91
25  393CS20024                        ROSHANI KUMARI   76  72
26  393CS20025  SACHIDANANDA MADIVALESHA BEVINAMARAD   17  30
27  393CS20026                   SHAREEKA GUDIYATTAM   58  49
28  393CS21706                  SNEHA ASHOK DODAMANI    4  24
29  393CS20028                        SPURTI S PATIL   86  70
30  393CS20029                       TANISHK BIRADAR   24  87
31  393CS20030                         UMARBIN PATIL   20  11
32  393CS21707                       VARSHA GALAGALI   37  58
33  393CS20018                            NEHA PATIL   31  94
34  393CS17018                        RAHUL BADAKURI    7  31
35  393CS20031                 VIDYA BABUGOUDA PATIL   95  77
36  393CS20032                       VIVEK CHOUDHARY   61  84
37  393CS17009          HAVINAL SHRIDHAR MALLIKARJUN   88  83
38  393CS17015                     OMKAR SHARANARTHI   76  31
39  393CS17018                        RAHUL BADAKURI    7  31
40  393CS21702              BIRADAR GURURAJ SIDHARUD   77  70
41  393CS21703                   GURUNATH DESHAPANDE   43  27
42  393CS21704                  MANJU SHIVAJI CHAVAN   10  14
43  393CS21706                  SNEHA ASHOK DODAMANI   90  22
44  393CS21707                       VARSHA GALAGALI   44  45
45  393CS20008                   JAHID ALI BALABATTI   23  45
46  393CS21706                  SNEHA ASHOK DODAMANI    4  24
47  393CS20028                        SPURTI S PATIL   86  70
48  393CS20030                         UMARBIN PATIL   20  11

# Adding the attribute

In [15]:
df['total']=b['OSA']+b["CN"]

In [16]:
df

        Reg_no                                  Name  OSA  CN  total
0   393CS21707                       VARSHA GALAGALI   44  45     89
1   393CS20001              ABHINAV PRASANNA NAIKODI   97  47    144
2   393CS20001              ABHINAV PRASANNA NAIKODI   97  47    144
3   393CS20002                          AKASH TORAVI   97  52    149
4   393CS21702              BIRADAR GURURAJ SIDHARUD   75  21     96
5   393CS20005                DUGIWADE PRACHI SANJAY   11  23     34
6   393CS21703                   GURUNATH DESHAPANDE   87  92    179
7   393CS20006           HARSHAD MAHAMMADSAB WALIKAR   45  78    123
8   393CS20007                    IRAMNAAZ JAMKHANDI   97  17    114
9   393CS20001              ABHINAV PRASANNA NAIKODI   97  47    144
10  393CS20008                   JAHID ALI BALABATTI   23  45     68
11  393CS20009                KRISHNA MAHADEV JADHAV   87  65    152
12  393CS20010                        LAXMI NAVALAGI   61  39    100
13  393CS20011                      MAIBOOBSAB NADAF   33  39     72
14  393CS21704                  MANJU SHIVAJI CHAVAN   53  44     97
15  393CS20012                  MISBA BUDANSAB MOMIN   56  62    118
16  393CS20013                   MODI AVADOOT MAHESH   22  65     87
17  393CS20015                     NADAF NIHAL NASIM   45  20     65
18  393CS20016                    NANDINI NITIN MODI   25  15     40
19  393CS20017               NEELAVANI VARSHA VITTAL   90  74    164
20  393CS20018                            NEHA PATIL   31  94    125
21  393CS20019                               NIKHEEL   93   3     96
22  393CS20020                POOJA RAJSHEKHAR ARABI   41  89    130
23  393CS20022                       PRAJWAL D DHAGE   32  57     89
24  393CS20023                        RENUKA ARAKERI   90  91    181
25  393CS20024                        ROSHANI KUMARI   76  72    148
26  393CS20025  SACHIDANANDA MADIVALESHA BEVINAMARAD   17  30     47
27  393CS20026                   SHAREEKA GUDIYATTAM   58  49    107
28  393CS21706                  SNEHA ASHOK DODAMANI    4  24     28
29  393CS20028                        SPURTI S PATIL   86  70    156
30  393CS20029                       TANISHK BIRADAR   24  87    111
31  393CS20030                         UMARBIN PATIL   20  11     31
32  393CS21707                       VARSHA GALAGALI   37  58     95
33  393CS20018                            NEHA PATIL   31  94    125
34  393CS17018                        RAHUL BADAKURI    7  31     38
35  393CS20031                 VIDYA BABUGOUDA PATIL   95  77    172
36  393CS20032                       VIVEK CHOUDHARY   61  84    145
37  393CS17009          HAVINAL SHRIDHAR MALLIKARJUN   88  83    171
38  393CS17015                     OMKAR SHARANARTHI   76  31    107
39  393CS17018                        RAHUL BADAKURI    7  31     38
40  393CS21702              BIRADAR GURURAJ SIDHARUD   77  70    147
41  393CS21703                   GURUNATH DESHAPANDE   43  27     70
42  393CS21704                  MANJU SHIVAJI CHAVAN   10  14     24
43  393CS21706                  SNEHA ASHOK DODAMANI   90  22    112
44  393CS21707                       VARSHA GALAGALI   44  45     89
45  393CS20008                   JAHID ALI BALABATTI   23  45     68
46  393CS21706                  SNEHA ASHOK DODAMANI    4  24     28
47  393CS20028                        SPURTI S PATIL   86  70    156
48  393CS20030                         UMARBIN PATIL   20  11     31

In [17]:
df['percentage']=df['total']/200*100

In [24]:
df1=pd.DataFrame([
    ['393CS2002',"Rahul",34,56,134,67.5]
],columns=["Reg_no","Name","OSA","CN","total","percentage"])

In [25]:
ans=df.append(df1)

C:\Users\Hp\AppData\Local\Temp\ipykernel_19800\3729128217.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  ans=df.append(df1)

In [26]:
ans.isna().sum()

Reg_no        0
Name          0
OSA           0
CN            0
total         0
percentage    0
dtype: int64

In [27]:
ans

,Reg_no,Name,OSA,CN,total,percentage
0,393CS21707,VARSHA GALAGALI,44,45,89,44.5
1,393CS20001,ABHINAV PRASANNA NAIKODI,97,47,144,72.0
2,393CS20001,ABHINAV PRASANNA NAIKODI,97,47,144,72.0
3,393CS20002,AKASH TORAVI,97,52,149,74.5
4,393CS21702,BIRADAR GURURAJ SIDHARUD,75,21,96,48.0
5,393CS20005,DUGIWADE PRACHI SANJAY,11,23,34,17.0
6,393CS21703,GURUNATH DESHAPANDE,87,92,179,89.5
7,393CS20006,HARSHAD MAHAMMADSAB WALIKAR,45,78,123,61.5
8,393CS20007,IRAMNAAZ JAMKHANDI,97,17,114,57.0
9,393CS20001,ABHINAV PRASANNA NAIKODI,97,47,144,72.0
10,393CS20008,JAHID ALI BALABATTI,23,45,68,34.0
11,393CS20009,KRISHNA MAHADEV JADHAV,87,65,152,76.0
12,393CS20010,LAXMI NAVALAGI,61,39,100,50.0
13,393CS20011,MAIBOOBSAB NADAF,33,39,72,36.0
14,393CS21704,MANJU SHIVAJI CHAVAN,53,44,97,48.5
15,393CS20012,MISBA BUDANSAB MOMIN,56,62,118,59.0
16,393CS20013,MODI AVADOOT MAHESH,22,65,87,43.5
17,393CS20015,NADAF NIHAL NASIM,45,20,65,32.5
18,393CS20016,NANDINI NITIN MODI,25,15,40,20.0
19,393CS20017,NEELAVANI VARSHA VITTAL,90,74,164,82.0
20,393CS20018,NEHA PATIL,31,94,125,62.5
21,393CS20019,NIKHEEL,93,3,96,48.0
22,393CS20020,POOJA RAJSHEKHAR ARABI,41,89,130,65.0
23,393CS20022,PRAJWAL D DHAGE,32,57,89,44.5
24,393CS20023,RENUKA ARAKERI,90,91,181,90.5
25,393CS20024,ROSHANI KUMARI,76,72,148,74.0
26,393CS20025,SACHIDANANDA MADIVALESHA BEVINAMARAD,17,30,47,23.5
27,393CS20026,SHAREEKA GUDIYATTAM,58,49,107,53.5
28,393CS21706,SNEHA ASHOK DODAMANI,4,24,28,14.0
29,393CS20028,SPURTI S PATIL,86,70,156,78.0
30,393CS20029,TANISHK BIRADAR,24,87,111,55.5
31,393CS20030,UMARBIN PATIL,20,11,31,15.5
32,393CS21707,VARSHA GALAGALI,37,58,95,47.5
33,393CS20018,NEHA PATIL,31,94,125,62.5
34,393CS17018,RAHUL BADAKURI,7,31,38,19.0
35,393CS20031,VIDYA BABUGOUDA PATIL,95,77,172,86.0
36,393CS20032,VIVEK CHOUDHARY,61,84,145,72.5
37,393CS17009,HAVINAL SHRIDHAR MALLIKARJUN,88,83,171,85.5
38,393CS17015,OMKAR SHARANARTHI,76,31,107,53.5
39,393CS17018,RAHUL BADAKURI,7,31,38,19.0
40,393CS21702,BIRADAR GURURAJ SIDHARUD,77,70,147,73.5
41,393CS21703,GURUNATH DESHAPANDE,43,27,70,35.0
42,393CS21704,MANJU SHIVAJI CHAVAN,10,14,24,12.0
43,393CS21706,SNEHA ASHOK DODAMANI,90,22,112,56.0
44,393CS21707,VARSHA GALAGALI,44,45,89,44.5
45,393CS20008,JAHID ALI BALABATTI,23,45,68,34.0
46,393CS21706,SNEHA ASHOK DODAMANI,4,24,28,14.0
47,393CS20028,SPURTI S PATIL,86,70,156,78.0
48,393CS20030,UMARBIN PATIL,20,11,31,15.5
0,393CS2002,Rahul,34,56,134,67.5